e-gov/cvi

libs/storybook/src/lib/stories/colors.stories.mdx

Remove reference to the Veera Design System

chore: update colors.stories.mdx

---

apps/ui-e2e/src/component/breadcrumbs.component.cy.ts
libs/styles/src/lib/scss/components/_breadcrumbs.scss
libs/ui/src/lib/breadcrumbs/breadcrumbs.component.html
libs/ui/src/lib/breadcrumbs/breadcrumbs.component.stories.ts

Show a more compact breadcrumb in smaller devices
Author: Ceisi Peik

feat(ng): custom mobile breadcrumb EBS-191 STPA-204

---

libs/styles/src/lib/scss/components/_select.scss
libs/ui/src/lib/select/select.component.html
libs/ui/src/lib/select/select.component.stories.ts
libs/ui/src/lib/select/select.component.ts

Added the ability to disable select component either by using component input or angular forms.

feat: add disabled state to select component

---

.github/ISSUE_TEMPLATE/BUG-REPORT.yml
.github/ISSUE_TEMPLATE/FEATURE-REQUEST.yml

Added issue form-based templates for bugs and feature requests.

docs(github): added issue templates for bugs and feature requests

---

.github/ISSUE_TEMPLATE/BUG-REPORT.yml
.github/ISSUE_TEMPLATE/FEATURE-REQUEST.yml

Fixes #49 and introduces a few DX improvements to the issue templates.

fix(github): minor issue template fixes

---

apps/ui-e2e/src/component/form-item.component.cy.ts
apps/ui-e2e/src/component/textarea.component.cy.ts
libs/styles/src/lib/scss/_apply.scss
libs/styles/src/lib/scss/components/_textfield-with-cdk.scss
libs/styles/src/lib/scss/main.scss
libs/ui/src/lib/textarea/textarea.component.html
libs/ui/src/lib/textarea/textarea.component.stories.ts
libs/ui/src/lib/textarea/textarea.component.ts
libs/ui/src/lib/textarea/textarea.html.stories.ts

fix(ui): fixed an issue where Angular textarea component would not restore its height

---

apps/ui-e2e/src/component/tab-group.component.cy.ts
libs/styles/src/lib/scss/components/_tab-group.scss
libs/ui/src/lib/tabs/tab-group.component.html
libs/ui/src/lib/tabs/tab-group.component.stories.ts
libs/ui/src/lib/tabs/tab-group.component.ts
libs/ui/src/lib/tabs/tab-group.html.stories.ts

fix(ui): made tabs accessible

---

libs/styles/src/lib/scss/components/_select.scss
libs/ui/src/lib/select/select-items-list.ts
libs/ui/src/lib/select/select.component.html
libs/ui/src/lib/select/select.component.stories.ts
libs/ui/src/lib/select/select.component.ts

Added loading state to select component.
Also fixed a minor issue where text [object Object] was displayed in filtering input when value had been selected.

feat: add loading state to select component

---

libs/ui/src/lib/select/select-items-list.ts
libs/ui/src/lib/select/select.component.stories.ts
libs/ui/src/lib/select/select.component.ts

added to possibility to sort items in select component drop-down

feat(ui): add sorting to select component

---

apps/ria/src/app/app.component.ts
apps/ria/src/app/app.module.ts
libs/ui/src/lib/character-counter/character-counter.component.ts
libs/ui/src/lib/character-counter/character-counter.directive.ts
libs/ui/src/lib/character-counter/character-counter.spec.ts
libs/ui/src/lib/input/input.component.ts
libs/ui/src/lib/select/select.component.stories.ts
libs/ui/src/lib/select/select.component.ts
libs/ui/src/lib/steps/steps/steps.component.stories.ts
libs/ui/src/lib/tabs/tab-group.component.stories.ts
libs/ui/src/lib/tabs/tab-group.component.ts
libs/ui/src/lib/textarea/textarea.component.ts
package-lock.json

Textarea, input and the character counter directive do not work properly inside tabs because when the content is visible change detection wont run using "OnPush" change detection until user interacts with the form.
Also fixes an issue with the character counter not getting re-drawn when the form control is updated using the controls patch or set methods.

fix(ng): change detection inside tab component EBS-335 STPA-245

---

README.md

Well placed icons make README.md files more readable (and fun).

chore: improve readme format

---

libs/react-ui/src/lib/button/button.tsx

Not a real PR, just a pipeline test.

refactor(react): set default appearance and button size

---

.stylelintrc.js
libs/styles/src/lib/scss/components/_table.scss
package.json

fix(styles): fixed an issue where running npm run lint:css would not yield any results  

---

libs/ui/src/lib/tabs/tab-group.component.spec.ts
libs/ui/src/lib/tabs/tab-group.component.stories.ts
libs/ui/src/lib/tabs/tab-group.component.ts

Added an emitter so we could do effects related to the tab content in case the user switches tabs.

feat(ng): provide an emitter for active tab changes EBS-729

---

.stylelintrc.js
libs/styles/src/lib/scss/components/_status-badge.scss
libs/ui/src/lib/status-badge/status-badge.component.html
libs/ui/src/lib/status-badge/status-badge.component.stories.ts
libs/ui/src/lib/status-badge/status-badge.html.stories.ts

fix(ng): status badge class format, clarify a stylelint linting error message

---

libs/storybook/.storybook/preview.js

feat(storybook): expand story source code in the Docs tab by default

---

libs/storybook/src/lib/directives/storybook-input/storybook-input.directive.ts
libs/storybook/src/lib/stories/icons/list.stories.mdx
libs/storybook/src/lib/storybook.module.ts
libs/styles/src/lib/scss/main.scss
libs/styles/src/lib/scss/storybook/components/_input.scss
libs/ui/src/lib/table-of-contents/generated-table-of-contents/generated-table-of-contents.component.ts

feat(storybook): add search in the icons list

---

libs/styles/src/lib/scss/components/_datepicker.scss
libs/styles/src/lib/scss/components/_select.scss
libs/styles/src/lib/scss/components/_textfield.scss
libs/styles/src/lib/scss/settings/variables/_other.scss
libs/ui/src/lib/datepicker/datepicker.component.stories.ts
libs/ui/src/lib/form-item/form-item.component.stories.ts

Unifies focus outline, border color, and height of `cvi-select`, `cvi-textfield`, `cvi-datepicker`.
Resolves #145.

fix(styles): made styles of inline form elements consistent

---

libs/storybook/.storybook/preview.js
libs/styles/src/lib/scss/components/_datepicker.scss
libs/ui/src/lib/datepicker/datepicker.component.stories.ts

fix(styles): fixed broken appearance of cvi-datepicker when on non-white background

---

libs/styles/src/lib/scss/components/_table.scss
libs/ui/src/lib/table/table.component.stories.ts
libs/ui/src/lib/table/table.html.stories.ts

fix(styles): fix(styles): fixed cvi-table body cell not wrapping strings that are too long and forcing the table to become too wide

---

libs/ui/src/lib/accordion/accordion.component.ts

feat(ng): add output to accordion
EBS-802, STPA-268

feat(ng): emit accordion toggle event

---

libs/styles/src/lib/scss/components/_breadcrumbs.scss
libs/ui/src/lib/breadcrumbs/breadcrumbs.component.html
libs/ui/src/lib/breadcrumbs/breadcrumbs.component.stories.ts
libs/ui/src/lib/breadcrumbs/breadcrumbs.component.ts
libs/ui/src/lib/breadcrumbs/breadcrumbs.html.stories.ts
libs/ui/src/lib/ui.module.ts

BREAKING CHANGE: breadcrumb component input

feat: breadcrumbs without link EBS-904 STPA-268

---

libs/styles/src/lib/scss/components/_toast.scss
libs/ui/src/lib/toast/toast.service.stories.ts

Set title line height and font weight explicitly. Handle longer strings in content.

feat: toast style modifications EBS-996 STPA-264

---

README.md

docs(all): added a clarification on configuring .npmrc file

---

libs/storybook/src/lib/stories/angular.stories.mdx
libs/storybook/src/lib/stories/icons/installation.stories.mdx
libs/storybook/src/lib/stories/ng-diagrams.stories.mdx
libs/storybook/src/lib/stories/styles/installation.stories.mdx

docs(all): mention an installation requirement of configuring the .npmrc file in the package-specific docs

---

libs/storybook/.storybook/preview.js
libs/storybook/src/lib/stories/icons/list.stories.mdx

feat(storybook): Added a new background color to the Storybook and set it to the Icons list page to allow for faster discovery of fixed fills

---

.github/ISSUE_TEMPLATE/BUG-REPORT.yml
README.md
libs/storybook/src/lib/stories/angular.stories.mdx

feat(github): added links to an example Angular app at codesandbox.io to the documentation

---

libs/react-ui/src/lib/button/button.spec.tsx

nx run react-ui:build:production failed.

fix(ui): import jest for react tests

---

libs/styles/src/lib/scss/components/_html-section.scss
libs/ui/src/lib/html-section/html-section.component.stories.ts

Opened a new and fixed PR. Previous is https://github.com/e-gov/cvi/pull/233. Could not commit into VJ branch

feat(ui): add nested list option for html section EBS-1547
